const std = @import("std");
const mesh_mod = @import("../mesh.zig");

// ASCII PLY is the first non-OBJ export because it maps directly onto the current
// mesh model: vertices plus arbitrary polygon faces, without forcing triangulation.
pub fn write(mesh: *const mesh_mod.Mesh, writer: anytype) !void {
    try writeHeader(mesh, writer);
    try writeVertices(mesh, writer);
    try writeFaces(mesh, writer);
}

fn writeHeader(mesh: *const mesh_mod.Mesh, writer: anytype) !void {
    try writer.writeAll("ply\n");
    try writer.writeAll("format ascii 1.0\n");
    try writer.writeAll("comment generated by blender-zig\n");
    try writer.print("element vertex {d}\n", .{mesh.vertexCount()});
    try writer.writeAll("property float x\n");
    try writer.writeAll("property float y\n");
    try writer.writeAll("property float z\n");
    try writer.print("element face {d}\n", .{mesh.faceCount()});
    try writer.writeAll("property list uchar int vertex_indices\n");
    try writer.writeAll("end_header\n");
}

fn writeVertices(mesh: *const mesh_mod.Mesh, writer: anytype) !void {
    for (mesh.positions.items) |position| {
        try writer.print("{} {} {}\n", .{ position.x, position.y, position.z });
    }
}

fn writeFaces(mesh: *const mesh_mod.Mesh, writer: anytype) !void {
    for (0..mesh.faceCount()) |face_index| {
        const range = mesh.faceVertexRange(face_index);
        const verts = mesh.corner_verts.items[range.start..range.end];
        try writer.print("{d}", .{verts.len});
        for (verts) |vert| {
            try writer.print(" {d}", .{vert});
        }
        try writer.writeByte('\n');
    }
}

pub fn writeFile(mesh: *const mesh_mod.Mesh, path: []const u8) !void {
    const file = try std.fs.cwd().createFile(path, .{ .truncate = true });
    defer file.close();

    var file_buffer: [4096]u8 = undefined;
    var file_writer = file.writer(&file_buffer);
    const writer = &file_writer.interface;
    try write(mesh, writer);
    try writer.flush();
}

test "ply writer emits polygon faces without triangulating" {
    var mesh = try mesh_mod.Mesh.init(std.testing.allocator);
    defer mesh.deinit();

    _ = try mesh.appendVertex(.{ .x = 0, .y = 0, .z = 0 });
    _ = try mesh.appendVertex(.{ .x = 1, .y = 0, .z = 0 });
    _ = try mesh.appendVertex(.{ .x = 1, .y = 1, .z = 0 });
    _ = try mesh.appendVertex(.{ .x = 0, .y = 1, .z = 0 });
    try mesh.appendFace(&[_]u32{ 0, 1, 2, 3 }, null);
    try mesh.rebuildEdgesFromFaces();

    var bytes = std.ArrayList(u8).empty;
    defer bytes.deinit(std.testing.allocator);

    try write(&mesh, bytes.writer(std.testing.allocator));
    try std.testing.expect(std.mem.indexOf(u8, bytes.items, "element vertex 4\n") != null);
    try std.testing.expect(std.mem.indexOf(u8, bytes.items, "element face 1\n") != null);
    try std.testing.expect(std.mem.indexOf(u8, bytes.items, "\n4 0 1 2 3\n") != null);
}

test "ply writer preserves loose-edge meshes as vertex-only files" {
    var mesh = try mesh_mod.Mesh.init(std.testing.allocator);
    defer mesh.deinit();

    _ = try mesh.appendVertex(.{ .x = 0, .y = 0, .z = 0 });
    _ = try mesh.appendVertex(.{ .x = 1, .y = 0, .z = 0 });
    try mesh.appendEdge(0, 1);

    var bytes = std.ArrayList(u8).empty;
    defer bytes.deinit(std.testing.allocator);

    try write(&mesh, bytes.writer(std.testing.allocator));
    try std.testing.expect(std.mem.indexOf(u8, bytes.items, "element vertex 2\n") != null);
    try std.testing.expect(std.mem.indexOf(u8, bytes.items, "element face 0\n") != null);
}
